package com.tu.hibernate.entity;
// Generated Oct 18, 2018 11:18:50 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region")
public class Region implements java.io.Serializable {

	private int regionId;
	private String regionName;
	private Set<User> users = new HashSet<User>(0);
	private Set<Team> teams = new HashSet<Team>(0);
	private Set<User> users_1 = new HashSet<User>(0);

	public Region() {
	}

	public Region(int regionId, String regionName) {
		this.regionId = regionId;
		this.regionName = regionName;
	}

	public Region(int regionId, String regionName, Set<User> users, Set<Team> teams, Set<User> users_1) {
		this.regionId = regionId;
		this.regionName = regionName;
		this.users = users;
		this.teams = teams;
		this.users_1 = users_1;
	}

	@Id

	@Column(name = "region_id", unique = true, nullable = false)
	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	@Column(name = "regionName", nullable = false)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<User> getUsers_1() {
		return this.users_1;
	}

	public void setUsers_1(Set<User> users_1) {
		this.users_1 = users_1;
	}

}
