package com.tu.hibernate.entity;
// Generated Oct 18, 2018 11:18:50 AM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.FetchType;
import javax.persistence.FieldResult;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

import org.hibernate.annotations.NamedNativeQuery;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team")
@SqlResultSetMapping(
		name = "TeamResult", 
		entities = {
				@EntityResult(entityClass = com.tu.hibernate.entity.Team.class, 
				fields = {@FieldResult(name = "teamId", column = "team_Id"), 
						  @FieldResult(name = "teamName", column = "teamName") }),

				@EntityResult(entityClass = com.tu.hibernate.entity.Region.class, 
				fields = {@FieldResult(name = "regionId", column = "region_id") }) })
public class Team implements java.io.Serializable {

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Team [teamId=" + teamId + ", region=" + region + ", name=" + teamName + ", users=" + users + "]";
	}

	private int teamId;
	private Region region;
	private String teamName;
	private Set<User> users = new HashSet<User>(0);

	public Team() {
	}

	public Team(int teamId, Region region, String teamName) {
		this.teamId = teamId;
		this.region = region;
		this.teamName = teamName;
	}

	public Team(int teamId, Region region, String teamName, Set<User> users) {
		this.teamId = teamId;
		this.region = region;
		this.teamName = teamName;
		this.users = users;
	}

	@Id

	@Column(name = "team_id", unique = true, nullable = false)
	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region_id", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "teamName", nullable = false)
	public String getTeamName() {
		return this.teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "team")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
